#!/usr/bin/env python3
"""Generate the runtime version module from pyproject.toml."""

from __future__ import annotations

import tomllib
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent.parent
PYPROJECT_PATH = ROOT_DIR / "pyproject.toml"
VERSION_MODULE_PATH = ROOT_DIR / "_version.py"


def main() -> None:
    """Write the project version to the generated runtime module."""
    with PYPROJECT_PATH.open("rb") as file:
        version = tomllib.load(file)["project"]["version"]

    if not isinstance(version, str) or not version.strip():
        raise ValueError("pyproject.toml 中的 project.version 必须是非空字符串")

    VERSION_MODULE_PATH.write_text(
        "# This file is generated by scripts/generate_version.py.\n"
        "# Do not edit it manually.\n"
        f"__version__ = {version!r}\n",
        encoding="utf-8",
    )
    print(version)


if __name__ == "__main__":
    main()
